services:
  read_the_docs:
    build: .
    container_name: read_the_docs
    image: mcp/read_the_docs
    volumes:
      - documents:/app/documents
    ports:
      - "6274:6274"
      - "6277:6277"

volumes:
  documents: